
:overview:
  :label: Overview
  :icon: info
  :attributes:
    - :name: name
      :label: Name
      :field_type: name
    - :name: universe_id
      :label: Universe
      :field_type: universe
    - :name: description
      :label: Description
    - :name: type_of
      :label: Type of building
    - :name: alternate_names
      :label: Alternate names
    - :name:
      :label: Tags
      :field_type: tags
:occupants:
  :label: Occupants
  :icon: recent_actors
  :attributes:
    - :name: owner
      :label: Owner
    - :name: tenants
      :label: Tenants
    - :name: affiliation
      :label: Affiliation
    - :name: capacity
      :label: Capacity
    - :name: price
      :label: Price
    - :name: animals
      :label: Animals
:design:
  :label: Design
  :icon: format_paint
  :attributes:
    - :name: architectural_style
      :label: Architectural style
    - :name: facade
      :label: Facade
    - :name: roof
      :label: Roof
    - :name: dimensions
      :label: Dimensions
    - :name: floor_count
      :label: Floor count
    - :name: flooring
      :label: Flooring
    - :name: walls
      :label: Walls
:purpose:
  :label: Usage
  :icon: extension
  :attributes:
    - :name: bedrooms
      :label: Bedrooms
    - :name: baths
      :label: Baths
    - :name: purpose
      :label: Purpose
    - :name: permits
      :label: Permits
:location:
  :label: Location
  :icon: location_on
  :attributes:
    - :name: address
      :label: Address
:history:
  :label: History
  :icon: date_range
  :attributes:
    - :name: constructed_year
      :label: Constructed year
    - :name: construction_cost
      :label: Construction cost
    - :name: architect
      :label: Architect
    - :name: developer
      :label: Developer
    - :name: notable_events
      :label: Notable events
:gallery:
  :label: Gallery
  :icon: photo_library
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private Notes
      :description: Private notes are <em>always</em> visible to only you, even if content is made public and shared.
